package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.BankAccount;
import mm.aeon.com.zgen.entity.BankAccountExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BankAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    long countByExample(BankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int deleteByExample(BankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int insert(BankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int insertSelective(BankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    List<BankAccount> selectByExampleWithRowbounds(BankAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    List<BankAccount> selectByExample(BankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    BankAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BankAccount record, @Param("example") BankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BankAccount record, @Param("example") BankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bank_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BankAccount record);
}