package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.CrudTest;
import mm.aeon.com.zgen.entity.CrudTestExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CrudTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    long countByExample(CrudTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int deleteByExample(CrudTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer crudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int insert(CrudTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int insertSelective(CrudTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    List<CrudTest> selectByExampleWithRowbounds(CrudTestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    List<CrudTest> selectByExample(CrudTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    CrudTest selectByPrimaryKey(Integer crudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CrudTest record, @Param("example") CrudTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CrudTest record, @Param("example") CrudTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CrudTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CrudTest record);
}