package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.Dealer;
import mm.aeon.com.zgen.entity.DealerExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    long countByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int deleteByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int insertSelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    List<Dealer> selectByExampleWithRowbounds(DealerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    List<Dealer> selectByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    Dealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dealer record);
}