package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.InspectVehicle;
import mm.aeon.com.zgen.entity.InspectVehicleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InspectVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    long countByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int deleteByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inspectVehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int insert(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int insertSelective(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    List<InspectVehicle> selectByExampleWithRowbounds(InspectVehicleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    List<InspectVehicle> selectByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    InspectVehicle selectByPrimaryKey(Integer inspectVehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InspectVehicle record, @Param("example") InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InspectVehicle record, @Param("example") InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InspectVehicle record);
}