package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.InspectVehicleDriver;
import mm.aeon.com.zgen.entity.InspectVehicleDriverExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InspectVehicleDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    long countByExample(InspectVehicleDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int deleteByExample(InspectVehicleDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inspectVehicleDriverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int insert(InspectVehicleDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int insertSelective(InspectVehicleDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    List<InspectVehicleDriver> selectByExampleWithRowbounds(InspectVehicleDriverExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    List<InspectVehicleDriver> selectByExample(InspectVehicleDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    InspectVehicleDriver selectByPrimaryKey(Integer inspectVehicleDriverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InspectVehicleDriver record, @Param("example") InspectVehicleDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InspectVehicleDriver record, @Param("example") InspectVehicleDriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InspectVehicleDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InspectVehicleDriver record);
}