package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.ItemVehicle;
import mm.aeon.com.zgen.entity.ItemVehicleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ItemVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    long countByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int deleteByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int insert(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int insertSelective(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    List<ItemVehicle> selectByExampleWithRowbounds(ItemVehicleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    List<ItemVehicle> selectByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    ItemVehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemVehicle record, @Param("example") ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemVehicle record, @Param("example") ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemVehicle record);
}