package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.PortTerminal;
import mm.aeon.com.zgen.entity.PortTerminalExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PortTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    long countByExample(PortTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int deleteByExample(PortTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int insert(PortTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int insertSelective(PortTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    List<PortTerminal> selectByExampleWithRowbounds(PortTerminalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    List<PortTerminal> selectByExample(PortTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    PortTerminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PortTerminal record, @Param("example") PortTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PortTerminal record, @Param("example") PortTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PortTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.port_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PortTerminal record);
}