package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.VehicleDealer;
import mm.aeon.com.zgen.entity.VehicleDealerExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VehicleDealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    long countByExample(VehicleDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int deleteByExample(VehicleDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int insert(VehicleDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int insertSelective(VehicleDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    List<VehicleDealer> selectByExampleWithRowbounds(VehicleDealerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    List<VehicleDealer> selectByExample(VehicleDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    VehicleDealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VehicleDealer record, @Param("example") VehicleDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VehicleDealer record, @Param("example") VehicleDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VehicleDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VehicleDealer record);
}