package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.VehicleInfo;
import mm.aeon.com.zgen.entity.VehicleInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VehicleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    long countByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int deleteByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int insert(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int insertSelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    List<VehicleInfo> selectByExampleWithRowbounds(VehicleInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    List<VehicleInfo> selectByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    VehicleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VehicleInfo record);
}