package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.Yard;
import mm.aeon.com.zgen.entity.YardExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface YardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    long countByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int deleteByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int insert(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int insertSelective(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    List<Yard> selectByExampleWithRowbounds(YardExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    List<Yard> selectByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    Yard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Yard record, @Param("example") YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Yard record, @Param("example") YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.yard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Yard record);
}