package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.ZoneColumn;
import mm.aeon.com.zgen.entity.ZoneColumnExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZoneColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    long countByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int deleteByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int insert(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int insertSelective(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    List<ZoneColumn> selectByExampleWithRowbounds(ZoneColumnExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    List<ZoneColumn> selectByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    ZoneColumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZoneColumn record, @Param("example") ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZoneColumn record, @Param("example") ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.zone_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZoneColumn record);
}