package mm.aeon.com.zconfig;

/**
 * 
 * Constant message for error and messages.
 */
public class MessageCode {
	/* Common */
	public static final String SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
	public static final String UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
	public static final String INVALID_REQUEST_PARAMETER = "INVALID_REQUEST_PARAMETER";
	public static final String DB_PROCESS_ERROR = "DB_PROCESS_ERROR";
	public static final String INVALID_TOKEN = "INVALID_TOKEN";
	public static final String USR_PWD_INCORRECT = "USR_PWD_INCORRECT";
	public static final String CONFIRM_PWD_NOT_MATCH = "CONFIRM_PWD_NOT_MATCH";
	public static final String OLD_PASSWORD_NOT_MATCH = "OLD_PASSWORD_NOT_MATCH";
	public static final String DUPLICATED_USERNAME = "DUPLICATED_USERNAME";
	public static final String VALUE_REQUIRED = "VALUE_REQUIRED";
	public static final String AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
	public static final String AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
	public static final String UNAUTHORIZED = "UNAUTHORIZED";
	public static final String IO_ERROR = "IO_ERROR";
	public static final String REQUIRED_INPUT = "REQUIRED_INPUT";
	public static final String DUPLICATED_NRC_NO_CORE_SYSTEM = "DUPLICATED_NRC_NO_CORE_SYSTEM";
	public static final String DUPLICATED_CUSTOMER_INFO = "DUPLICATED_CUSTOMER_INFO";
	public static final String DUPLICATED_NRC_NO = "DUPLICATED_NRC_NO";
	public static final String DUPLICATED_PHONE_NO = "DUPLICATED_PHONE_NO";
	public static final String DUPLICATED_IMPORT_NRC_NO = "DUPLICATED_IMPORT_NRC_NO";
	public static final String DUPLICATED_IMPORT_PHONE_NO = "DUPLICATED_IMPORT_PHONE_NO";
	public static final String INVALID_EMAIL = "INVALID_EMAIL";
	public static final String CANCELATION_EXCEED = "CANCELATION_EXCEED";
	public static final String INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD";
	public static final String UNMATCH_CONFIRM_NEW_PASSWORD = "UNMATCH_CONFIRM_NEW_PASSWORD";
	public static final String MISSING_COMPANY_INFO = "MISSING_COMPANY_INFO";
	public static final String MISSING_IMPORT_CUSTOMER_INFO = "MISSING_IMPORT_CUSTOMER_INFO";
	public static final String MISSING_CUSTOMER_AGREEMENT_INFO = "MISSING_CUSTOMER_AGREEMENT_INFO";
	public static final String NOT_EXIST_CUSTOMER_INFO = "NOT_EXIST_CUSTOMER_INFO";
	public static final String NOT_EXIST_CUSTOMER_ANSWER = "NOT_EXIST_CUSTOMER_ANSWER";
	public static final String INVALID_CUSTOMER_ANSWER = "INVALID_CUSTOMER_ANSWER";
	public static final String PASSWORD_WEAK = "PASSWORD_WEAK";
	public static final String INVALID_PASSWORD_LENGTH = "INVALID_PASSWORD_LENGTH";
	public static final String INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
	public static final String COUPON_REDEEM = "COUPON_REDEEM";
	public static final String INVALID_AGREEMENT_NO = "INVALID_AGREEMENT_NO";
	public static final String INVALID_MEMBER_INFO = "INVALID_MEMBER_INFO";
	public static final String INVALID_CHARACTER = "INVALID_CHARACTER";
	public static final String INVALID_AGE = "INVALID_AGE";
	public static final String ACCOUNT_LOCKED = "ACCOUNT_LOCKED";
	public static final String INVALID_LOAN_TERM_MINIMUM = "INVALID_LOAN_TERM_MINIMUM";
	public static final String INVALID_FINANCE_AMOUNT_MINIMUM = "INVALID_FINANCE_AMOUNT_MINIMUM";
	public static final String INVALID_FINANCE_AMOUNT_MAXIMUM = "INVALID_FINANCE_AMOUNT_MAXIMUM";
	public static final String INVALID_LOAN_TERM = "INVALID_LOAN_TERM";
	public static final String CUSTOMER_INFO_ALREADY_EDIT = "CUSTOMER_INFO_ALREADY_EDIT";
	public static final String REQUIRED_PHOTO_BYTE = "REQUIRED_PHOTO_BYTE";
	public static final String INSUFFICIENT_ATTACHMENT_INFO = "INSUFFICIENT_ATTACHMENT_INFO";
	public static final String INSUFFICIENT_MULTIPART_FILE_LIST_SIZE = "INSUFFICIENT_MULTIPART_FILE_LIST_SIZE";
	public static final String ATTACHMENT_INFO_LIST_SIZE = "ATTACHMENT_INFO_LIST_SIZE";
	public static final String INVALID_FINANCE_AMOUNT = "INVALID_FINANCE_AMOUNT";
	public static final String INVALID_TOTAL_FINANCE_AMOUNT = "INVALID_TOTAL_FINANCE_AMOUNT";
	public static final String APPLICATION_LIMIT = "APPLICATION_LIMIT";
	public static final String INVALID_APPLICATION_INFO = "INVALID_APPLICATION_INFO";
	public static final String APPLICATION_ALREADY_CANCELLED = "APPLICATION_ALREADY_CANCELLED";
	public static final String APPLICATION_ALREADY_UPDATED = "APPLICATION_ALREADY_UPDATED";
	public static final String APPLICATION_ALREADY_SAVED_DRAFT = "APPLICATION_ALREADY_SAVED_DRAFT";
	public static final String PURCHASE_ALREADY_CONFIRMED = "PURCHASE_ALREADY_CONFIRMED";
	public static final String PURCHASE_ALREADY_COMPLETED = "PURCHASE_ALREADY_COMPLETED";
	public static final String FILE_WRITING_ERROR = "FILE_WRITING_ERROR";
	public static final String REQUIRED_ATTACHMENT_FILE_NAME = "REQUIRED_ATTACHMENT_FILE_NAME";
	public static final String NOT_SAME_ATTACHMENT_FILE_NAME_AND_MULTIPART_FILE_NAME = "NOT_SAME_ATTACHMENT_FILE_NAME_AND_MULTIPART_FILE_NAME";
	public static final String NOT_EXIST_VEHICLE_INFO = "NOT_EXIST_VEHICLE_INFO";
	public static final String INVALID_PARKING_ZONE_COLUMN = "INVALID_PARKING_ZONE_COLUMN";
}
