package mm.aeon.com.zgen.entity;

public class CrudTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crud_test.crud_id
     *
     * @mbg.generated
     */
    private Integer crudId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crud_test.crud_name
     *
     * @mbg.generated
     */
    private String crudName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crud_test.crud_no
     *
     * @mbg.generated
     */
    private Integer crudNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crud_test.crud_id
     *
     * @return the value of public.crud_test.crud_id
     *
     * @mbg.generated
     */
    public Integer getCrudId() {
        return crudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crud_test.crud_id
     *
     * @param crudId the value for public.crud_test.crud_id
     *
     * @mbg.generated
     */
    public void setCrudId(Integer crudId) {
        this.crudId = crudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crud_test.crud_name
     *
     * @return the value of public.crud_test.crud_name
     *
     * @mbg.generated
     */
    public String getCrudName() {
        return crudName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crud_test.crud_name
     *
     * @param crudName the value for public.crud_test.crud_name
     *
     * @mbg.generated
     */
    public void setCrudName(String crudName) {
        this.crudName = crudName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crud_test.crud_no
     *
     * @return the value of public.crud_test.crud_no
     *
     * @mbg.generated
     */
    public Integer getCrudNo() {
        return crudNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crud_test.crud_no
     *
     * @param crudNo the value for public.crud_test.crud_no
     *
     * @mbg.generated
     */
    public void setCrudNo(Integer crudNo) {
        this.crudNo = crudNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crud_test
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", crudId=").append(crudId);
        sb.append(", crudName=").append(crudName);
        sb.append(", crudNo=").append(crudNo);
        sb.append("]");
        return sb.toString();
    }
}