package mm.aeon.com.zgen.entity;

import java.util.Date;

public class Dealer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.dealer_code
     *
     * @mbg.generated
     */
    private String dealerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.dealer_name
     *
     * @mbg.generated
     */
    private String dealerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.created_user
     *
     * @mbg.generated
     */
    private Integer createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.updated_user
     *
     * @mbg.generated
     */
    private Integer updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.phone_no
     *
     * @mbg.generated
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.contact_position
     *
     * @mbg.generated
     */
    private String contactPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.contact_phone_no
     *
     * @mbg.generated
     */
    private String contactPhoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.contract_start_date
     *
     * @mbg.generated
     */
    private Date contractStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.contract_end_date
     *
     * @mbg.generated
     */
    private Date contractEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.account_information
     *
     * @mbg.generated
     */
    private String accountInformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.disabled
     *
     * @mbg.generated
     */
    private Boolean disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.id
     *
     * @return the value of public.dealer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.id
     *
     * @param id the value for public.dealer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.dealer_code
     *
     * @return the value of public.dealer.dealer_code
     *
     * @mbg.generated
     */
    public String getDealerCode() {
        return dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.dealer_code
     *
     * @param dealerCode the value for public.dealer.dealer_code
     *
     * @mbg.generated
     */
    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.dealer_name
     *
     * @return the value of public.dealer.dealer_name
     *
     * @mbg.generated
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.dealer_name
     *
     * @param dealerName the value for public.dealer.dealer_name
     *
     * @mbg.generated
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.delete_flg
     *
     * @return the value of public.dealer.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.delete_flg
     *
     * @param deleteFlg the value for public.dealer.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.created_user
     *
     * @return the value of public.dealer.created_user
     *
     * @mbg.generated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.created_user
     *
     * @param createdUser the value for public.dealer.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.created_date
     *
     * @return the value of public.dealer.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.created_date
     *
     * @param createdDate the value for public.dealer.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.updated_user
     *
     * @return the value of public.dealer.updated_user
     *
     * @mbg.generated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.updated_user
     *
     * @param updatedUser the value for public.dealer.updated_user
     *
     * @mbg.generated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.updated_date
     *
     * @return the value of public.dealer.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.updated_date
     *
     * @param updatedDate the value for public.dealer.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.address
     *
     * @return the value of public.dealer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.address
     *
     * @param address the value for public.dealer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.phone_no
     *
     * @return the value of public.dealer.phone_no
     *
     * @mbg.generated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.phone_no
     *
     * @param phoneNo the value for public.dealer.phone_no
     *
     * @mbg.generated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.contact_name
     *
     * @return the value of public.dealer.contact_name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.contact_name
     *
     * @param contactName the value for public.dealer.contact_name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.contact_position
     *
     * @return the value of public.dealer.contact_position
     *
     * @mbg.generated
     */
    public String getContactPosition() {
        return contactPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.contact_position
     *
     * @param contactPosition the value for public.dealer.contact_position
     *
     * @mbg.generated
     */
    public void setContactPosition(String contactPosition) {
        this.contactPosition = contactPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.contact_phone_no
     *
     * @return the value of public.dealer.contact_phone_no
     *
     * @mbg.generated
     */
    public String getContactPhoneNo() {
        return contactPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.contact_phone_no
     *
     * @param contactPhoneNo the value for public.dealer.contact_phone_no
     *
     * @mbg.generated
     */
    public void setContactPhoneNo(String contactPhoneNo) {
        this.contactPhoneNo = contactPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.contract_start_date
     *
     * @return the value of public.dealer.contract_start_date
     *
     * @mbg.generated
     */
    public Date getContractStartDate() {
        return contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.contract_start_date
     *
     * @param contractStartDate the value for public.dealer.contract_start_date
     *
     * @mbg.generated
     */
    public void setContractStartDate(Date contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.contract_end_date
     *
     * @return the value of public.dealer.contract_end_date
     *
     * @mbg.generated
     */
    public Date getContractEndDate() {
        return contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.contract_end_date
     *
     * @param contractEndDate the value for public.dealer.contract_end_date
     *
     * @mbg.generated
     */
    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.account_information
     *
     * @return the value of public.dealer.account_information
     *
     * @mbg.generated
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.account_information
     *
     * @param accountInformation the value for public.dealer.account_information
     *
     * @mbg.generated
     */
    public void setAccountInformation(String accountInformation) {
        this.accountInformation = accountInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.disabled
     *
     * @return the value of public.dealer.disabled
     *
     * @mbg.generated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.disabled
     *
     * @param disabled the value for public.dealer.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dealerCode=").append(dealerCode);
        sb.append(", dealerName=").append(dealerName);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", address=").append(address);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", contactName=").append(contactName);
        sb.append(", contactPosition=").append(contactPosition);
        sb.append(", contactPhoneNo=").append(contactPhoneNo);
        sb.append(", contractStartDate=").append(contractStartDate);
        sb.append(", contractEndDate=").append(contractEndDate);
        sb.append(", accountInformation=").append(accountInformation);
        sb.append(", disabled=").append(disabled);
        sb.append("]");
        return sb.toString();
    }
}