package mm.aeon.com.zgen.entity;

import java.util.Date;

public class InspectVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.inspect_vehicle_id
     *
     * @mbg.generated
     */
    private Integer inspectVehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    private Integer vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.trailer_id
     *
     * @mbg.generated
     */
    private Integer trailerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.car_body_good_flag
     *
     * @mbg.generated
     */
    private Boolean carBodyGoodFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.engine_good_flag
     *
     * @mbg.generated
     */
    private Boolean engineGoodFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.interior_good_flag
     *
     * @mbg.generated
     */
    private Boolean interiorGoodFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.parking_column_id
     *
     * @mbg.generated
     */
    private Integer parkingColumnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.parking_status
     *
     * @mbg.generated
     */
    private Integer parkingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.created_user
     *
     * @mbg.generated
     */
    private Integer createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.updated_user
     *
     * @mbg.generated
     */
    private Integer updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.owner_driver_flag
     *
     * @mbg.generated
     */
    private Boolean ownerDriverFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle.trailer_flag
     *
     * @mbg.generated
     */
    private Boolean trailerFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.inspect_vehicle_id
     *
     * @return the value of public.inspect_vehicle.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public Integer getInspectVehicleId() {
        return inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.inspect_vehicle_id
     *
     * @param inspectVehicleId the value for public.inspect_vehicle.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public void setInspectVehicleId(Integer inspectVehicleId) {
        this.inspectVehicleId = inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.vehicle_id
     *
     * @return the value of public.inspect_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.vehicle_id
     *
     * @param vehicleId the value for public.inspect_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.task_id
     *
     * @return the value of public.inspect_vehicle.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.task_id
     *
     * @param taskId the value for public.inspect_vehicle.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.trailer_id
     *
     * @return the value of public.inspect_vehicle.trailer_id
     *
     * @mbg.generated
     */
    public Integer getTrailerId() {
        return trailerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.trailer_id
     *
     * @param trailerId the value for public.inspect_vehicle.trailer_id
     *
     * @mbg.generated
     */
    public void setTrailerId(Integer trailerId) {
        this.trailerId = trailerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.car_body_good_flag
     *
     * @return the value of public.inspect_vehicle.car_body_good_flag
     *
     * @mbg.generated
     */
    public Boolean getCarBodyGoodFlag() {
        return carBodyGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.car_body_good_flag
     *
     * @param carBodyGoodFlag the value for public.inspect_vehicle.car_body_good_flag
     *
     * @mbg.generated
     */
    public void setCarBodyGoodFlag(Boolean carBodyGoodFlag) {
        this.carBodyGoodFlag = carBodyGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.engine_good_flag
     *
     * @return the value of public.inspect_vehicle.engine_good_flag
     *
     * @mbg.generated
     */
    public Boolean getEngineGoodFlag() {
        return engineGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.engine_good_flag
     *
     * @param engineGoodFlag the value for public.inspect_vehicle.engine_good_flag
     *
     * @mbg.generated
     */
    public void setEngineGoodFlag(Boolean engineGoodFlag) {
        this.engineGoodFlag = engineGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.interior_good_flag
     *
     * @return the value of public.inspect_vehicle.interior_good_flag
     *
     * @mbg.generated
     */
    public Boolean getInteriorGoodFlag() {
        return interiorGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.interior_good_flag
     *
     * @param interiorGoodFlag the value for public.inspect_vehicle.interior_good_flag
     *
     * @mbg.generated
     */
    public void setInteriorGoodFlag(Boolean interiorGoodFlag) {
        this.interiorGoodFlag = interiorGoodFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.remark
     *
     * @return the value of public.inspect_vehicle.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.remark
     *
     * @param remark the value for public.inspect_vehicle.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.parking_column_id
     *
     * @return the value of public.inspect_vehicle.parking_column_id
     *
     * @mbg.generated
     */
    public Integer getParkingColumnId() {
        return parkingColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.parking_column_id
     *
     * @param parkingColumnId the value for public.inspect_vehicle.parking_column_id
     *
     * @mbg.generated
     */
    public void setParkingColumnId(Integer parkingColumnId) {
        this.parkingColumnId = parkingColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.parking_status
     *
     * @return the value of public.inspect_vehicle.parking_status
     *
     * @mbg.generated
     */
    public Integer getParkingStatus() {
        return parkingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.parking_status
     *
     * @param parkingStatus the value for public.inspect_vehicle.parking_status
     *
     * @mbg.generated
     */
    public void setParkingStatus(Integer parkingStatus) {
        this.parkingStatus = parkingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.created_date
     *
     * @return the value of public.inspect_vehicle.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.created_date
     *
     * @param createdDate the value for public.inspect_vehicle.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.created_user
     *
     * @return the value of public.inspect_vehicle.created_user
     *
     * @mbg.generated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.created_user
     *
     * @param createdUser the value for public.inspect_vehicle.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.updated_date
     *
     * @return the value of public.inspect_vehicle.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.updated_date
     *
     * @param updatedDate the value for public.inspect_vehicle.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.updated_user
     *
     * @return the value of public.inspect_vehicle.updated_user
     *
     * @mbg.generated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.updated_user
     *
     * @param updatedUser the value for public.inspect_vehicle.updated_user
     *
     * @mbg.generated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.del_flag
     *
     * @return the value of public.inspect_vehicle.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.del_flag
     *
     * @param delFlag the value for public.inspect_vehicle.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.owner_driver_flag
     *
     * @return the value of public.inspect_vehicle.owner_driver_flag
     *
     * @mbg.generated
     */
    public Boolean getOwnerDriverFlag() {
        return ownerDriverFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.owner_driver_flag
     *
     * @param ownerDriverFlag the value for public.inspect_vehicle.owner_driver_flag
     *
     * @mbg.generated
     */
    public void setOwnerDriverFlag(Boolean ownerDriverFlag) {
        this.ownerDriverFlag = ownerDriverFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle.trailer_flag
     *
     * @return the value of public.inspect_vehicle.trailer_flag
     *
     * @mbg.generated
     */
    public Boolean getTrailerFlag() {
        return trailerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle.trailer_flag
     *
     * @param trailerFlag the value for public.inspect_vehicle.trailer_flag
     *
     * @mbg.generated
     */
    public void setTrailerFlag(Boolean trailerFlag) {
        this.trailerFlag = trailerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inspectVehicleId=").append(inspectVehicleId);
        sb.append(", vehicleId=").append(vehicleId);
        sb.append(", taskId=").append(taskId);
        sb.append(", trailerId=").append(trailerId);
        sb.append(", carBodyGoodFlag=").append(carBodyGoodFlag);
        sb.append(", engineGoodFlag=").append(engineGoodFlag);
        sb.append(", interiorGoodFlag=").append(interiorGoodFlag);
        sb.append(", remark=").append(remark);
        sb.append(", parkingColumnId=").append(parkingColumnId);
        sb.append(", parkingStatus=").append(parkingStatus);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", ownerDriverFlag=").append(ownerDriverFlag);
        sb.append(", trailerFlag=").append(trailerFlag);
        sb.append("]");
        return sb.toString();
    }
}