package mm.aeon.com.zgen.entity;

import java.util.Date;

public class InspectVehicleDriver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.inspect_vehicle_driver_id
     *
     * @mbg.generated
     */
    private Integer inspectVehicleDriverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.inspect_vehicle_id
     *
     * @mbg.generated
     */
    private Integer inspectVehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.created_user
     *
     * @mbg.generated
     */
    private Integer createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.updated_user
     *
     * @mbg.generated
     */
    private Integer updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_driver.driver_id
     *
     * @mbg.generated
     */
    private Integer driverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.inspect_vehicle_driver_id
     *
     * @return the value of public.inspect_vehicle_driver.inspect_vehicle_driver_id
     *
     * @mbg.generated
     */
    public Integer getInspectVehicleDriverId() {
        return inspectVehicleDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.inspect_vehicle_driver_id
     *
     * @param inspectVehicleDriverId the value for public.inspect_vehicle_driver.inspect_vehicle_driver_id
     *
     * @mbg.generated
     */
    public void setInspectVehicleDriverId(Integer inspectVehicleDriverId) {
        this.inspectVehicleDriverId = inspectVehicleDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.inspect_vehicle_id
     *
     * @return the value of public.inspect_vehicle_driver.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public Integer getInspectVehicleId() {
        return inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.inspect_vehicle_id
     *
     * @param inspectVehicleId the value for public.inspect_vehicle_driver.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public void setInspectVehicleId(Integer inspectVehicleId) {
        this.inspectVehicleId = inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.created_date
     *
     * @return the value of public.inspect_vehicle_driver.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.created_date
     *
     * @param createdDate the value for public.inspect_vehicle_driver.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.created_user
     *
     * @return the value of public.inspect_vehicle_driver.created_user
     *
     * @mbg.generated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.created_user
     *
     * @param createdUser the value for public.inspect_vehicle_driver.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.updated_date
     *
     * @return the value of public.inspect_vehicle_driver.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.updated_date
     *
     * @param updatedDate the value for public.inspect_vehicle_driver.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.updated_user
     *
     * @return the value of public.inspect_vehicle_driver.updated_user
     *
     * @mbg.generated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.updated_user
     *
     * @param updatedUser the value for public.inspect_vehicle_driver.updated_user
     *
     * @mbg.generated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.del_flag
     *
     * @return the value of public.inspect_vehicle_driver.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.del_flag
     *
     * @param delFlag the value for public.inspect_vehicle_driver.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_driver.driver_id
     *
     * @return the value of public.inspect_vehicle_driver.driver_id
     *
     * @mbg.generated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_driver.driver_id
     *
     * @param driverId the value for public.inspect_vehicle_driver.driver_id
     *
     * @mbg.generated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_driver
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inspectVehicleDriverId=").append(inspectVehicleDriverId);
        sb.append(", inspectVehicleId=").append(inspectVehicleId);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", driverId=").append(driverId);
        sb.append("]");
        return sb.toString();
    }
}