package mm.aeon.com.zgen.entity;

import java.util.Date;

public class InspectVehicleAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.inspect_vehicle_attachment_id
     *
     * @mbg.generated
     */
    private Integer inspectVehicleAttachmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.inspect_vehicle_id
     *
     * @mbg.generated
     */
    private Integer inspectVehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.created_user
     *
     * @mbg.generated
     */
    private Integer createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.updated_user
     *
     * @mbg.generated
     */
    private Integer updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inspect_vehicle_attachment.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.inspect_vehicle_attachment_id
     *
     * @return the value of public.inspect_vehicle_attachment.inspect_vehicle_attachment_id
     *
     * @mbg.generated
     */
    public Integer getInspectVehicleAttachmentId() {
        return inspectVehicleAttachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.inspect_vehicle_attachment_id
     *
     * @param inspectVehicleAttachmentId the value for public.inspect_vehicle_attachment.inspect_vehicle_attachment_id
     *
     * @mbg.generated
     */
    public void setInspectVehicleAttachmentId(Integer inspectVehicleAttachmentId) {
        this.inspectVehicleAttachmentId = inspectVehicleAttachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.inspect_vehicle_id
     *
     * @return the value of public.inspect_vehicle_attachment.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public Integer getInspectVehicleId() {
        return inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.inspect_vehicle_id
     *
     * @param inspectVehicleId the value for public.inspect_vehicle_attachment.inspect_vehicle_id
     *
     * @mbg.generated
     */
    public void setInspectVehicleId(Integer inspectVehicleId) {
        this.inspectVehicleId = inspectVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.file_path
     *
     * @return the value of public.inspect_vehicle_attachment.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.file_path
     *
     * @param filePath the value for public.inspect_vehicle_attachment.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.created_date
     *
     * @return the value of public.inspect_vehicle_attachment.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.created_date
     *
     * @param createdDate the value for public.inspect_vehicle_attachment.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.created_user
     *
     * @return the value of public.inspect_vehicle_attachment.created_user
     *
     * @mbg.generated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.created_user
     *
     * @param createdUser the value for public.inspect_vehicle_attachment.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.updated_date
     *
     * @return the value of public.inspect_vehicle_attachment.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.updated_date
     *
     * @param updatedDate the value for public.inspect_vehicle_attachment.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.updated_user
     *
     * @return the value of public.inspect_vehicle_attachment.updated_user
     *
     * @mbg.generated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.updated_user
     *
     * @param updatedUser the value for public.inspect_vehicle_attachment.updated_user
     *
     * @mbg.generated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inspect_vehicle_attachment.del_flag
     *
     * @return the value of public.inspect_vehicle_attachment.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inspect_vehicle_attachment.del_flag
     *
     * @param delFlag the value for public.inspect_vehicle_attachment.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inspect_vehicle_attachment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inspectVehicleAttachmentId=").append(inspectVehicleAttachmentId);
        sb.append(", inspectVehicleId=").append(inspectVehicleId);
        sb.append(", filePath=").append(filePath);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}