package mm.aeon.com.zgen.entity;

public class ItemVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_vehicle.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    private Integer vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_vehicle.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_vehicle.id
     *
     * @return the value of public.item_vehicle.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_vehicle.id
     *
     * @param id the value for public.item_vehicle.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_vehicle.vehicle_id
     *
     * @return the value of public.item_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_vehicle.vehicle_id
     *
     * @param vehicleId the value for public.item_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_vehicle.item_id
     *
     * @return the value of public.item_vehicle.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_vehicle.item_id
     *
     * @param itemId the value for public.item_vehicle.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_vehicle
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vehicleId=").append(vehicleId);
        sb.append(", itemId=").append(itemId);
        sb.append("]");
        return sb.toString();
    }
}