package mm.aeon.com.zgen.entity;

import java.util.Date;

public class Trailer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.license_no
     *
     * @mbg.generated
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.trailer_type
     *
     * @mbg.generated
     */
    private String trailerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.disabled
     *
     * @mbg.generated
     */
    private Boolean disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.trailer_id
     *
     * @mbg.generated
     */
    private String trailerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trailer.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.id
     *
     * @return the value of public.trailer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.id
     *
     * @param id the value for public.trailer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.license_no
     *
     * @return the value of public.trailer.license_no
     *
     * @mbg.generated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.license_no
     *
     * @param licenseNo the value for public.trailer.license_no
     *
     * @mbg.generated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.trailer_type
     *
     * @return the value of public.trailer.trailer_type
     *
     * @mbg.generated
     */
    public String getTrailerType() {
        return trailerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.trailer_type
     *
     * @param trailerType the value for public.trailer.trailer_type
     *
     * @mbg.generated
     */
    public void setTrailerType(String trailerType) {
        this.trailerType = trailerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.description
     *
     * @return the value of public.trailer.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.description
     *
     * @param description the value for public.trailer.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.disabled
     *
     * @return the value of public.trailer.disabled
     *
     * @mbg.generated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.disabled
     *
     * @param disabled the value for public.trailer.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.created_date
     *
     * @return the value of public.trailer.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.created_date
     *
     * @param createdDate the value for public.trailer.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.updated_date
     *
     * @return the value of public.trailer.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.updated_date
     *
     * @param updatedDate the value for public.trailer.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.created_by
     *
     * @return the value of public.trailer.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.created_by
     *
     * @param createdBy the value for public.trailer.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.updated_by
     *
     * @return the value of public.trailer.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.updated_by
     *
     * @param updatedBy the value for public.trailer.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.delete_flg
     *
     * @return the value of public.trailer.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.delete_flg
     *
     * @param deleteFlg the value for public.trailer.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.trailer_id
     *
     * @return the value of public.trailer.trailer_id
     *
     * @mbg.generated
     */
    public String getTrailerId() {
        return trailerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.trailer_id
     *
     * @param trailerId the value for public.trailer.trailer_id
     *
     * @mbg.generated
     */
    public void setTrailerId(String trailerId) {
        this.trailerId = trailerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trailer.barcode
     *
     * @return the value of public.trailer.barcode
     *
     * @mbg.generated
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trailer.barcode
     *
     * @param barcode the value for public.trailer.barcode
     *
     * @mbg.generated
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trailer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", trailerType=").append(trailerType);
        sb.append(", description=").append(description);
        sb.append(", disabled=").append(disabled);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", trailerId=").append(trailerId);
        sb.append(", barcode=").append(barcode);
        sb.append("]");
        return sb.toString();
    }
}