package mm.aeon.com.zgen.entity;

import java.util.Date;

public class VehicleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.dealer_id
     *
     * @mbg.generated
     */
    private Integer dealerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.chassis_no
     *
     * @mbg.generated
     */
    private String chassisNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.color_code
     *
     * @mbg.generated
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.first_vessel_name
     *
     * @mbg.generated
     */
    private String firstVesselName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.second_vessel_name
     *
     * @mbg.generated
     */
    private String secondVesselName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.cif
     *
     * @mbg.generated
     */
    private String cif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.etd_origin
     *
     * @mbg.generated
     */
    private String etdOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.etd_estimated_date
     *
     * @mbg.generated
     */
    private Date etdEstimatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.vessel_berthing_date
     *
     * @mbg.generated
     */
    private Date vesselBerthingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.etd_sin
     *
     * @mbg.generated
     */
    private Date etdSin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.eta
     *
     * @mbg.generated
     */
    private Date eta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.consignee_on_bl
     *
     * @mbg.generated
     */
    private String consigneeOnBl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.prod_mth
     *
     * @mbg.generated
     */
    private Date prodMth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.agent_name
     *
     * @mbg.generated
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.port_carried_out_date
     *
     * @mbg.generated
     */
    private Date portCarriedOutDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.port_carried_out_remark
     *
     * @mbg.generated
     */
    private String portCarriedOutRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.stock_of
     *
     * @mbg.generated
     */
    private String stockOf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.stock_date
     *
     * @mbg.generated
     */
    private Date stockDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.list_of_under_applying_purchase_permit_process
     *
     * @mbg.generated
     */
    private String listOfUnderApplyingPurchasePermitProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.audio_installation_date_mailed_on
     *
     * @mbg.generated
     */
    private String audioInstallationDateMailedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.audio_installation_date_installed_on
     *
     * @mbg.generated
     */
    private String audioInstallationDateInstalledOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.disabled
     *
     * @mbg.generated
     */
    private Boolean disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.created_user
     *
     * @mbg.generated
     */
    private Integer createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.updated_user
     *
     * @mbg.generated
     */
    private Integer updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.audio_install_required
     *
     * @mbg.generated
     */
    private Boolean audioInstallRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.discharge_port_id
     *
     * @mbg.generated
     */
    private Integer dischargePortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.license_no
     *
     * @mbg.generated
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.port_carried_unit
     *
     * @mbg.generated
     */
    private Integer portCarriedUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.discharge_port_plan_date
     *
     * @mbg.generated
     */
    private Date dischargePortPlanDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.discharge_port_actual_date
     *
     * @mbg.generated
     */
    private Date dischargePortActualDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.order_month
     *
     * @mbg.generated
     */
    private Date orderMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_info.order_by
     *
     * @mbg.generated
     */
    private String orderBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.id
     *
     * @return the value of public.vehicle_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.id
     *
     * @param id the value for public.vehicle_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.dealer_id
     *
     * @return the value of public.vehicle_info.dealer_id
     *
     * @mbg.generated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.dealer_id
     *
     * @param dealerId the value for public.vehicle_info.dealer_id
     *
     * @mbg.generated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.chassis_no
     *
     * @return the value of public.vehicle_info.chassis_no
     *
     * @mbg.generated
     */
    public String getChassisNo() {
        return chassisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.chassis_no
     *
     * @param chassisNo the value for public.vehicle_info.chassis_no
     *
     * @mbg.generated
     */
    public void setChassisNo(String chassisNo) {
        this.chassisNo = chassisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.model
     *
     * @return the value of public.vehicle_info.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.model
     *
     * @param model the value for public.vehicle_info.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.color
     *
     * @return the value of public.vehicle_info.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.color
     *
     * @param color the value for public.vehicle_info.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.color_code
     *
     * @return the value of public.vehicle_info.color_code
     *
     * @mbg.generated
     */
    public String getColorCode() {
        return colorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.color_code
     *
     * @param colorCode the value for public.vehicle_info.color_code
     *
     * @mbg.generated
     */
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.first_vessel_name
     *
     * @return the value of public.vehicle_info.first_vessel_name
     *
     * @mbg.generated
     */
    public String getFirstVesselName() {
        return firstVesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.first_vessel_name
     *
     * @param firstVesselName the value for public.vehicle_info.first_vessel_name
     *
     * @mbg.generated
     */
    public void setFirstVesselName(String firstVesselName) {
        this.firstVesselName = firstVesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.second_vessel_name
     *
     * @return the value of public.vehicle_info.second_vessel_name
     *
     * @mbg.generated
     */
    public String getSecondVesselName() {
        return secondVesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.second_vessel_name
     *
     * @param secondVesselName the value for public.vehicle_info.second_vessel_name
     *
     * @mbg.generated
     */
    public void setSecondVesselName(String secondVesselName) {
        this.secondVesselName = secondVesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.cif
     *
     * @return the value of public.vehicle_info.cif
     *
     * @mbg.generated
     */
    public String getCif() {
        return cif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.cif
     *
     * @param cif the value for public.vehicle_info.cif
     *
     * @mbg.generated
     */
    public void setCif(String cif) {
        this.cif = cif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.etd_origin
     *
     * @return the value of public.vehicle_info.etd_origin
     *
     * @mbg.generated
     */
    public String getEtdOrigin() {
        return etdOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.etd_origin
     *
     * @param etdOrigin the value for public.vehicle_info.etd_origin
     *
     * @mbg.generated
     */
    public void setEtdOrigin(String etdOrigin) {
        this.etdOrigin = etdOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.etd_estimated_date
     *
     * @return the value of public.vehicle_info.etd_estimated_date
     *
     * @mbg.generated
     */
    public Date getEtdEstimatedDate() {
        return etdEstimatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.etd_estimated_date
     *
     * @param etdEstimatedDate the value for public.vehicle_info.etd_estimated_date
     *
     * @mbg.generated
     */
    public void setEtdEstimatedDate(Date etdEstimatedDate) {
        this.etdEstimatedDate = etdEstimatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.vessel_berthing_date
     *
     * @return the value of public.vehicle_info.vessel_berthing_date
     *
     * @mbg.generated
     */
    public Date getVesselBerthingDate() {
        return vesselBerthingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.vessel_berthing_date
     *
     * @param vesselBerthingDate the value for public.vehicle_info.vessel_berthing_date
     *
     * @mbg.generated
     */
    public void setVesselBerthingDate(Date vesselBerthingDate) {
        this.vesselBerthingDate = vesselBerthingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.etd_sin
     *
     * @return the value of public.vehicle_info.etd_sin
     *
     * @mbg.generated
     */
    public Date getEtdSin() {
        return etdSin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.etd_sin
     *
     * @param etdSin the value for public.vehicle_info.etd_sin
     *
     * @mbg.generated
     */
    public void setEtdSin(Date etdSin) {
        this.etdSin = etdSin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.eta
     *
     * @return the value of public.vehicle_info.eta
     *
     * @mbg.generated
     */
    public Date getEta() {
        return eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.eta
     *
     * @param eta the value for public.vehicle_info.eta
     *
     * @mbg.generated
     */
    public void setEta(Date eta) {
        this.eta = eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.consignee_on_bl
     *
     * @return the value of public.vehicle_info.consignee_on_bl
     *
     * @mbg.generated
     */
    public String getConsigneeOnBl() {
        return consigneeOnBl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.consignee_on_bl
     *
     * @param consigneeOnBl the value for public.vehicle_info.consignee_on_bl
     *
     * @mbg.generated
     */
    public void setConsigneeOnBl(String consigneeOnBl) {
        this.consigneeOnBl = consigneeOnBl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.prod_mth
     *
     * @return the value of public.vehicle_info.prod_mth
     *
     * @mbg.generated
     */
    public Date getProdMth() {
        return prodMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.prod_mth
     *
     * @param prodMth the value for public.vehicle_info.prod_mth
     *
     * @mbg.generated
     */
    public void setProdMth(Date prodMth) {
        this.prodMth = prodMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.agent_name
     *
     * @return the value of public.vehicle_info.agent_name
     *
     * @mbg.generated
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.agent_name
     *
     * @param agentName the value for public.vehicle_info.agent_name
     *
     * @mbg.generated
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.port_carried_out_date
     *
     * @return the value of public.vehicle_info.port_carried_out_date
     *
     * @mbg.generated
     */
    public Date getPortCarriedOutDate() {
        return portCarriedOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.port_carried_out_date
     *
     * @param portCarriedOutDate the value for public.vehicle_info.port_carried_out_date
     *
     * @mbg.generated
     */
    public void setPortCarriedOutDate(Date portCarriedOutDate) {
        this.portCarriedOutDate = portCarriedOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.port_carried_out_remark
     *
     * @return the value of public.vehicle_info.port_carried_out_remark
     *
     * @mbg.generated
     */
    public String getPortCarriedOutRemark() {
        return portCarriedOutRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.port_carried_out_remark
     *
     * @param portCarriedOutRemark the value for public.vehicle_info.port_carried_out_remark
     *
     * @mbg.generated
     */
    public void setPortCarriedOutRemark(String portCarriedOutRemark) {
        this.portCarriedOutRemark = portCarriedOutRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.stock_of
     *
     * @return the value of public.vehicle_info.stock_of
     *
     * @mbg.generated
     */
    public String getStockOf() {
        return stockOf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.stock_of
     *
     * @param stockOf the value for public.vehicle_info.stock_of
     *
     * @mbg.generated
     */
    public void setStockOf(String stockOf) {
        this.stockOf = stockOf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.stock_date
     *
     * @return the value of public.vehicle_info.stock_date
     *
     * @mbg.generated
     */
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.stock_date
     *
     * @param stockDate the value for public.vehicle_info.stock_date
     *
     * @mbg.generated
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.list_of_under_applying_purchase_permit_process
     *
     * @return the value of public.vehicle_info.list_of_under_applying_purchase_permit_process
     *
     * @mbg.generated
     */
    public String getListOfUnderApplyingPurchasePermitProcess() {
        return listOfUnderApplyingPurchasePermitProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.list_of_under_applying_purchase_permit_process
     *
     * @param listOfUnderApplyingPurchasePermitProcess the value for public.vehicle_info.list_of_under_applying_purchase_permit_process
     *
     * @mbg.generated
     */
    public void setListOfUnderApplyingPurchasePermitProcess(String listOfUnderApplyingPurchasePermitProcess) {
        this.listOfUnderApplyingPurchasePermitProcess = listOfUnderApplyingPurchasePermitProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.audio_installation_date_mailed_on
     *
     * @return the value of public.vehicle_info.audio_installation_date_mailed_on
     *
     * @mbg.generated
     */
    public String getAudioInstallationDateMailedOn() {
        return audioInstallationDateMailedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.audio_installation_date_mailed_on
     *
     * @param audioInstallationDateMailedOn the value for public.vehicle_info.audio_installation_date_mailed_on
     *
     * @mbg.generated
     */
    public void setAudioInstallationDateMailedOn(String audioInstallationDateMailedOn) {
        this.audioInstallationDateMailedOn = audioInstallationDateMailedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.audio_installation_date_installed_on
     *
     * @return the value of public.vehicle_info.audio_installation_date_installed_on
     *
     * @mbg.generated
     */
    public String getAudioInstallationDateInstalledOn() {
        return audioInstallationDateInstalledOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.audio_installation_date_installed_on
     *
     * @param audioInstallationDateInstalledOn the value for public.vehicle_info.audio_installation_date_installed_on
     *
     * @mbg.generated
     */
    public void setAudioInstallationDateInstalledOn(String audioInstallationDateInstalledOn) {
        this.audioInstallationDateInstalledOn = audioInstallationDateInstalledOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.remark
     *
     * @return the value of public.vehicle_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.remark
     *
     * @param remark the value for public.vehicle_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.disabled
     *
     * @return the value of public.vehicle_info.disabled
     *
     * @mbg.generated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.disabled
     *
     * @param disabled the value for public.vehicle_info.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.delete_flg
     *
     * @return the value of public.vehicle_info.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.delete_flg
     *
     * @param deleteFlg the value for public.vehicle_info.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.created_user
     *
     * @return the value of public.vehicle_info.created_user
     *
     * @mbg.generated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.created_user
     *
     * @param createdUser the value for public.vehicle_info.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.created_date
     *
     * @return the value of public.vehicle_info.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.created_date
     *
     * @param createdDate the value for public.vehicle_info.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.updated_user
     *
     * @return the value of public.vehicle_info.updated_user
     *
     * @mbg.generated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.updated_user
     *
     * @param updatedUser the value for public.vehicle_info.updated_user
     *
     * @mbg.generated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.updated_date
     *
     * @return the value of public.vehicle_info.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.updated_date
     *
     * @param updatedDate the value for public.vehicle_info.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.audio_install_required
     *
     * @return the value of public.vehicle_info.audio_install_required
     *
     * @mbg.generated
     */
    public Boolean getAudioInstallRequired() {
        return audioInstallRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.audio_install_required
     *
     * @param audioInstallRequired the value for public.vehicle_info.audio_install_required
     *
     * @mbg.generated
     */
    public void setAudioInstallRequired(Boolean audioInstallRequired) {
        this.audioInstallRequired = audioInstallRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.discharge_port_id
     *
     * @return the value of public.vehicle_info.discharge_port_id
     *
     * @mbg.generated
     */
    public Integer getDischargePortId() {
        return dischargePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.discharge_port_id
     *
     * @param dischargePortId the value for public.vehicle_info.discharge_port_id
     *
     * @mbg.generated
     */
    public void setDischargePortId(Integer dischargePortId) {
        this.dischargePortId = dischargePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.license_no
     *
     * @return the value of public.vehicle_info.license_no
     *
     * @mbg.generated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.license_no
     *
     * @param licenseNo the value for public.vehicle_info.license_no
     *
     * @mbg.generated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.port_carried_unit
     *
     * @return the value of public.vehicle_info.port_carried_unit
     *
     * @mbg.generated
     */
    public Integer getPortCarriedUnit() {
        return portCarriedUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.port_carried_unit
     *
     * @param portCarriedUnit the value for public.vehicle_info.port_carried_unit
     *
     * @mbg.generated
     */
    public void setPortCarriedUnit(Integer portCarriedUnit) {
        this.portCarriedUnit = portCarriedUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.discharge_port_plan_date
     *
     * @return the value of public.vehicle_info.discharge_port_plan_date
     *
     * @mbg.generated
     */
    public Date getDischargePortPlanDate() {
        return dischargePortPlanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.discharge_port_plan_date
     *
     * @param dischargePortPlanDate the value for public.vehicle_info.discharge_port_plan_date
     *
     * @mbg.generated
     */
    public void setDischargePortPlanDate(Date dischargePortPlanDate) {
        this.dischargePortPlanDate = dischargePortPlanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.discharge_port_actual_date
     *
     * @return the value of public.vehicle_info.discharge_port_actual_date
     *
     * @mbg.generated
     */
    public Date getDischargePortActualDate() {
        return dischargePortActualDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.discharge_port_actual_date
     *
     * @param dischargePortActualDate the value for public.vehicle_info.discharge_port_actual_date
     *
     * @mbg.generated
     */
    public void setDischargePortActualDate(Date dischargePortActualDate) {
        this.dischargePortActualDate = dischargePortActualDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.order_month
     *
     * @return the value of public.vehicle_info.order_month
     *
     * @mbg.generated
     */
    public Date getOrderMonth() {
        return orderMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.order_month
     *
     * @param orderMonth the value for public.vehicle_info.order_month
     *
     * @mbg.generated
     */
    public void setOrderMonth(Date orderMonth) {
        this.orderMonth = orderMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_info.order_by
     *
     * @return the value of public.vehicle_info.order_by
     *
     * @mbg.generated
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_info.order_by
     *
     * @param orderBy the value for public.vehicle_info.order_by
     *
     * @mbg.generated
     */
    public void setOrderBy(String orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dealerId=").append(dealerId);
        sb.append(", chassisNo=").append(chassisNo);
        sb.append(", model=").append(model);
        sb.append(", color=").append(color);
        sb.append(", colorCode=").append(colorCode);
        sb.append(", firstVesselName=").append(firstVesselName);
        sb.append(", secondVesselName=").append(secondVesselName);
        sb.append(", cif=").append(cif);
        sb.append(", etdOrigin=").append(etdOrigin);
        sb.append(", etdEstimatedDate=").append(etdEstimatedDate);
        sb.append(", vesselBerthingDate=").append(vesselBerthingDate);
        sb.append(", etdSin=").append(etdSin);
        sb.append(", eta=").append(eta);
        sb.append(", consigneeOnBl=").append(consigneeOnBl);
        sb.append(", prodMth=").append(prodMth);
        sb.append(", agentName=").append(agentName);
        sb.append(", portCarriedOutDate=").append(portCarriedOutDate);
        sb.append(", portCarriedOutRemark=").append(portCarriedOutRemark);
        sb.append(", stockOf=").append(stockOf);
        sb.append(", stockDate=").append(stockDate);
        sb.append(", listOfUnderApplyingPurchasePermitProcess=").append(listOfUnderApplyingPurchasePermitProcess);
        sb.append(", audioInstallationDateMailedOn=").append(audioInstallationDateMailedOn);
        sb.append(", audioInstallationDateInstalledOn=").append(audioInstallationDateInstalledOn);
        sb.append(", remark=").append(remark);
        sb.append(", disabled=").append(disabled);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", audioInstallRequired=").append(audioInstallRequired);
        sb.append(", dischargePortId=").append(dischargePortId);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", portCarriedUnit=").append(portCarriedUnit);
        sb.append(", dischargePortPlanDate=").append(dischargePortPlanDate);
        sb.append(", dischargePortActualDate=").append(dischargePortActualDate);
        sb.append(", orderMonth=").append(orderMonth);
        sb.append(", orderBy=").append(orderBy);
        sb.append("]");
        return sb.toString();
    }
}