package mm.aeon.com.zgen.entity;

public class VehicleDealer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_dealer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_dealer.vehicle_id
     *
     * @mbg.generated
     */
    private Integer vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.vehicle_dealer.dealer_id
     *
     * @mbg.generated
     */
    private Integer dealerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_dealer.id
     *
     * @return the value of public.vehicle_dealer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_dealer.id
     *
     * @param id the value for public.vehicle_dealer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_dealer.vehicle_id
     *
     * @return the value of public.vehicle_dealer.vehicle_id
     *
     * @mbg.generated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_dealer.vehicle_id
     *
     * @param vehicleId the value for public.vehicle_dealer.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.vehicle_dealer.dealer_id
     *
     * @return the value of public.vehicle_dealer.dealer_id
     *
     * @mbg.generated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.vehicle_dealer.dealer_id
     *
     * @param dealerId the value for public.vehicle_dealer.dealer_id
     *
     * @mbg.generated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.vehicle_dealer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vehicleId=").append(vehicleId);
        sb.append(", dealerId=").append(dealerId);
        sb.append("]");
        return sb.toString();
    }
}